# Generated by Django 3.0.8 on 2020-07-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlahaberryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('logo', models.BooleanField(default=False)),
                ('banner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlahaBerrySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=100)),
                ('setting_value', models.TextField()),
            ],
        ),
    ]
