# Generated by Django 3.0.8 on 2020-07-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alahaberryphoto_alahaberrysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_description',
            field=models.TextField(blank=True, default='NA', max_length=250),
        ),
    ]
