# Generated by Django 3.0.8 on 2020-09-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200727_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='alahaberrysetting',
            name='unit_sale_charges',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
