# Generated by Django 3.0.8 on 2020-09-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alahaberrysetting_unit_sale_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alahaberrysetting',
            name='unit_sale_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
