# Generated by Django 3.0.8 on 2020-09-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200908_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='alahaberrysetting',
            name='favicon',
            field=models.ImageField(default='default.jpg', upload_to='application_images', verbose_name='Favicon 16X16'),
        ),
    ]
