# Generated by Django 3.0.8 on 2020-09-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alahaberrysetting_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_seller',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
