# Generated by Django 3.0.8 on 2020-09-25 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_packages', '0001_initial'),
        ('users', '0010_profile_new_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='years',
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription_packages.SubscriptionPackage'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
