# Generated by Django 3.0.8 on 2020-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_discounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discounts',
            new_name='Discount',
        ),
        migrations.AddField(
            model_name='profile',
            name='handle_orders',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
