# Generated by Django 3.0.8 on 2020-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200928_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alahaberrysetting',
            name='unit_sale_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Percentage charge on sale'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='handle_orders',
            field=models.BooleanField(default=False),
        ),
    ]
