# Generated by Django 3.0.8 on 2020-09-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_alahaberrysetting_unit_sale_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='alahaberrysetting',
            name='charges_on_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
