# Generated by Django 3.0.8 on 2020-09-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alahaberrysetting_charges_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alahaberrysetting',
            name='charges_on_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, null=True, verbose_name='Percentage charge on sale'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='affiliate_discount',
            field=models.IntegerField(default=25, verbose_name='Affiliate Discount %'),
        ),
    ]
