# Generated by Django 3.0.8 on 2020-10-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200928_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_id',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
