# Generated by Django 3.0.8 on 2020-10-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201021_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_name',
            field=models.CharField(default='Alahaberry', max_length=100),
        ),
    ]
