# Generated by Django 3.0.8 on 2020-10-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20201024_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='seller_id',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='ID'),
        ),
    ]
