# Generated by Django 3.0.8 on 2020-10-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201025_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alahaberrysetting',
            name='commission_rate_on_sale',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=5, null=True, verbose_name='Commission rate (%) on sale'),
        ),
    ]
