# Generated by Django 3.0.8 on 2021-02-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20201025_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='alahaberrysetting',
            name='cover_photo',
            field=models.ImageField(default='default.jpg', upload_to='application_images'),
        ),
    ]
