# Generated by Django 3.0.8 on 2021-07-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(blank=True, null=True, upload_to='homepage-slides')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
