# Generated by Django 3.0.8 on 2020-09-08 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('call_to_action', models.TextField()),
                ('link', models.CharField(max_length=250)),
                ('image', models.FileField(blank=True, null=True, upload_to='ad_media')),
                ('advertiser', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
