# Generated by Django 3.0.8 on 2020-09-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='call_to_action',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
