# Generated by Django 3.0.8 on 2020-09-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20200908_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='vertical',
            field=models.BooleanField(default=False),
        ),
    ]
