# Generated by Django 3.0.8 on 2020-09-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_advertisement_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='ad_media'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='ad_media'),
        ),
    ]
