# Generated by Django 3.0.8 on 2020-09-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20200908_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_media'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='ad_media', verbose_name='Short video ad'),
        ),
    ]
