# Generated by Django 3.0.8 on 2020-10-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0004_commission_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='commission_instance',
            field=models.CharField(default='Subscription', max_length=24, null=True),
        ),
    ]
