# Generated by Django 3.0.8 on 2020-07-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_pics'),
        ),
    ]
