# Generated by Django 3.0.8 on 2020-07-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_clerk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='category_image',
            new_name='category_image1',
        ),
        migrations.AddField(
            model_name='categorie',
            name='category_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='category_image2',
            field=models.ImageField(blank=True, null=True, upload_to='category_pics'),
        ),
    ]
