# Generated by Django 3.0.8 on 2020-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_damages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
