# Generated by Django 3.0.8 on 2020-08-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200829_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_new',
            field=models.BooleanField(default=True),
        ),
    ]
