# Generated by Django 3.0.8 on 2020-08-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_brand_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
