# Generated by Django 3.0.8 on 2020-09-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(default=0.0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_new',
            field=models.BooleanField(default=True, verbose_name='Brand New?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Discount?'),
        ),
    ]
