# Generated by Django 3.0.8 on 2020-09-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200904_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_new',
            field=models.BooleanField(default=True, verbose_name='Brand New Item!'),
        ),
    ]
