# Generated by Django 3.0.8 on 2020-10-25 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_order_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='When do you want item delivered?'),
        ),
    ]
