# Generated by Django 3.0.8 on 2020-10-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_attempts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
