# Generated by Django 3.0.8 on 2020-10-25 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20201025_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
