# Generated by Django 3.0.8 on 2020-10-25 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20201025_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producthit',
            old_name='date_viewed',
            new_name='last_viewed',
        ),
        migrations.AlterField(
            model_name='producthit',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_hit', to='products.Product'),
        ),
    ]
