# Generated by Django 3.0.8 on 2021-02-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_itemrequest_solditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solditem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
