# Generated by Django 3.0.8 on 2021-02-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20210228_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='delivered_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
