# Generated by Django 3.0.8 on 2021-03-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20210228_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='payment_made',
            field=models.BooleanField(default=False),
        ),
    ]
