# Generated by Django 3.0.8 on 2021-03-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_solditem_payment_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='seller_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
