# Generated by Django 3.0.8 on 2021-04-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_solditem_seller_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_damages', verbose_name='Image to highlight condition'),
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('image1', models.ImageField(blank=True, upload_to='product_colors', verbose_name='First image')),
                ('image2', models.ImageField(blank=True, upload_to='product_colors', verbose_name='Second image')),
                ('image3', models.ImageField(blank=True, upload_to='product_colors', verbose_name='Third image')),
                ('image4', models.ImageField(blank=True, upload_to='product_colors', verbose_name='Fourth image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
