# Generated by Django 3.0.8 on 2021-04-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20210404_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcolor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Color or type'),
        ),
    ]
